# This file was generated by GoReleaser. DO NOT EDIT.
cask "floe" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "9a24e0049a8a980ad0949ca365e74bfbbfe27b1c61051bf2a68f2579c8196038"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4e83d72a47c343e6fa1bd4d92cd7a46013e1c9e6423f0dafd0662ec24d8cec51"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ff84555287331a931de3c0b2e399530e6ae8d8c9904d5941285cbfce6109ebe"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5465c47d9767fa68369c3805415a717fa358362511e1569c9d12f8597ecf35f1"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "floe"
  desc "Secure peer-to-peer file transfer CLI"
  homepage "https://floe.one"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floe"

  # No zap stanza required

end
