# This file was generated by GoReleaser. DO NOT EDIT.
cask "floe" do
  version "1.10.8"

  on_macos do
    on_intel do
      sha256 "2f0da594c2168965e0a0330e0024d53bf527b73c6c778c17e66e5ca252065f7e"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9463627b52c1ba9a87f94497868abaecc599dd97d56bc3960ec8d703df19a959"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2b9c615508f8fb754edb6e17b400c7603c9b5e5039f896de7c26aac3d31fd5cd"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8638710c66ea701df0490646a85a4e8ef85b584fc761df6df254b3cbd9b8dd3b"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "floe"
  desc "Secure peer-to-peer file transfer CLI"
  homepage "https://floe.one"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floe"

  # No zap stanza required

end
