# This file was generated by GoReleaser. DO NOT EDIT.
cask "floe" do
  version "1.7.4"

  on_macos do
    on_intel do
      sha256 "8cf3049785d047462de3dd58d08414c63f9db011ccf10e471a079989eca64b17"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de3e7b07c95fd9ff41014ea9b9779b9dedc13972211310c2389ee11d1f8fa4ea"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0220e5e30a3b0b6072288339ff953c499bd9388fc40eb2ba9e0d510f2e89315"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5dee9ea15e054286b2b17d5a35ca7188f1f99ec83d6f1503c86b4f2bf371164d"
      url "https://github.com/jannskiee/floe/releases/download/v#{version}/floe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "floe"
  desc "Secure peer-to-peer file transfer CLI"
  homepage "https://floe.one"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "floe"

  # No zap stanza required

end
